### ISSUE TITLE
Upgrade to the latest CIS Benchmark rules for Microsoft Windows

### ISSUE THREAD

**Issue by Jnchi** [noma4i/puppet-windows_cis#1]
> For Microsoft Windows Server 2016 RTM (1607) (CIS Microsoft Windows Server 2016 RTM (Release 1607) Benchmark version 1.1.0) 
https://www.cisecurity.org/benchmark/microsoft_windows_server

**Comment by Jnchi** [comment]
Also, how much additional effort would be required to add the Desktop rules, https://www.cisecurity.org/benchmark/microsoft_windows_desktop

**Comment by noma4i** [comment]
Unfortunately applying rules needs testing so it's not just writing code. Every rule I have added was tested to be present on the target machine as Windows it quite fragile and I don't trust it. So it's complicated as Im not using windows anymore.

**Comment by Jnchi** [comment]
Fair enough, thanks for your hard work!
